POST http://127.0.0.1:8000/signup 
Content-Type: application/json

{ "username": "dsadasdasdasdasdsadasdasdasdasdasdasdasddsa", "password": "Pass1234!", "email": "adam1@mail.com" }

###

POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ "username": "admin", "password": "admin" }

###

POST http://127.0.0.1:8000/token_test 
Content-Type: application/json

{ "token": ""}

###

POST http://127.0.0.1:8000/logout
Content-Type: application/json

{ "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcxNjI1MzAzNywiaWF0IjoxNzA4NDc3MDM3LCJqdGkiOiI3NGQ1YzhiYThjM2Y0MjkyOTdmOWM4MTJkZDhhZWVlYSIsInVzZXJfaWQiOjF9.XFPgPmHlKtQxBg-6RA4IZUm4TgyfCa6PvxrEi_YNWVU"}