POST http://127.0.0.1:8000/signup 
Content-Type: application/json

{ "username": "niggernigger12", "password": "Pass12345678!", "email": "am@mail.com" }

###

POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ "username": "niggernigger", "password": "Pass12345678!" }

###

POST http://127.0.0.1:8000/token_test 
Content-Type: application/json

{ "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcxNjQ3MjI0OSwiaWF0IjoxNzA4Njk2MjQ5LCJqdGkiOiIzMjkxNGY2NGUwOGQ0Yjk4YWY5ZTZkYWFhNmM2YjIyZiIsInVzZXJfaWQiOjEsInVzZXJuYW1lIjoiYWRtaW4ifQ.Z5jb91CnlHTUzhnrn1lr0iW1c3RapDAurhZpd3WHFOk"}

###

POST http://127.0.0.1:8000/logout
Content-Type: application/json

{ "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcxNjI1MzAzNywiaWF0IjoxNzA4NDc3MDM3LCJqdGkiOiI3NGQ1YzhiYThjM2Y0MjkyOTdmOWM4MTJkZDhhZWVlYSIsInVzZXJfaWQiOjF9.XFPgPmHlKtQxBg-6RA4IZUm4TgyfCa6PvxrEi_YNWVU"}

###

POST  http://127.0.0.1:8000/token_refresh
Content-Type: application/json

{ "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcxNjQ4NDAxNywiaWF0IjoxNzA4NzA4MDE3LCJqdGkiOiI5YWMyMDM2MzFjZGY0NGRiYmQwMWZmZTZiZWFjY2Q1MiIsInVzZXJfaWQiOjEsInVzZXJuYW1lIjoiYWRtaW4ifQ.wOGGXKMS1nsmeDpQ1opq5z9GrlVfuicIMu_N0hEBXck"}

###

POST http://127.0.0.1:8000/user_delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA4NzIwNzk5LCJpYXQiOjE3MDg3MjA0OTksImp0aSI6IjQ5M2IzNzM1YTFjZDRiYTg4NWY0NzQwZjZiOTUxMGExIiwidXNlcl9pZCI6NywidXNlcm5hbWUiOiJuaWtvZGVtMTIzIn0.ogMW9IDAXCn4H9JYAKnqoiah50eqWbPz66OHYTpiXCo

{ "username": "nikodem123", "password": "Szwecja2000@" }
