# Generated by Django 5.0.3 on 2024-03-05 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Wrong username!', regex='^[a-z0-9](?:[a-z0-9]+[.\\-_]?)+[a-z0-9]$'), django.core.validators.MinLengthValidator(4)]),
        ),
    ]
