# Generated by Django 5.0.3 on 2024-03-22 19:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_is_email_confirmed_customuser_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default='', error_messages={'blank': 'blank', 'invalid': 'invalid', 'unique': 'not_unique'}, max_length=40, unique=True, validators=[api.models.username_validator]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'blank': 'blank', 'invalid': 'invalid', 'unique': 'not_unique'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'blank': 'blank', 'invalid': 'invalid', 'unique': 'not_unique'}, max_length=40, unique=True, validators=[api.models.username_validator]),
        ),
    ]
